### ISSUE TITLE
Cannot install in on both MacaOS and Ubuntu 20.04

### ISSUE THREAD

**Issue by liu-xiao-guo** [elastic/opbeans-frontend#44]
I cloned the project, and I used the following command to install and run the project.

npm install

Then I get the following error:

npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path /home/liuxg/nodejs/opbeans-frontend/node_modules/@elastic/apm-rum-react/node_modules/hoist-non-react-statics
npm ERR! dest /home/liuxg/nodejs/opbeans-frontend/node_modules/@elastic/apm-rum-react/node_modules/hoist-non-react-statics
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, rename '/home/liuxg/nodejs/opbeans-frontend/node_modules/@elastic/apm-rum-react/node_modules/hoist-non-react-statics' -> '/home/liuxg/nodejs/opbeans-frontend/node_modules/@elastic/apm-rum-react/node_modules/hoist-non-react-statics'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/liuxg/.npm/_logs/2021-02-04T05_26_45_902Z-debug.log

It is the same for Mac and Ubuntu.

Thanks & best regards

**Comment by kuisathaverat** [comment]
It supports only Node.js 12, on upper versions it fails to run `npm install`
